/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "CPU": {                                         "en": "CPU",                                             "de": "CPU",                                             "ru": "ЦПУ",                                             "pt": "CPU",                                             "nl": "CPU",                                             "fr": "CPU",                                             "it": "processore",                                      "es": "UPC",                                             "pl": "procesor",                                        "zh-cn": "中央处理器"},
    "Memory": {                                      "en": "Memory",                                          "de": "Speicher",                                        "ru": "Память",                                          "pt": "Memória",                                         "nl": "Geheugen",                                        "fr": "Mémoire",                                         "it": "Memoria",                                         "es": "Memoria",                                         "pl": "Pamięć",                                          "zh-cn": "记忆"},
    "Network": {                                     "en": "Network",                                         "de": "Netzwerk",                                        "ru": "сеть",                                            "pt": "Rede",                                            "nl": "Netwerk",                                         "fr": "Réseau",                                          "it": "Rete",                                            "es": "Red",                                             "pl": "Sieć",                                            "zh-cn": "网络"},
    "OPI-Monitor Adapter settings": {                "en": "OPI-Monitor Adapter settings",                    "de": "OPI-Monitor Adapter Einstellungen",               "ru": "Настройки адаптера OPI-монитора",                 "pt": "Configurações do adaptador OPI-Monitor",          "nl": "OPI-Monitor Adapterinstellingen",                 "fr": "Paramètres de l'adaptateur OPI-Monitor",          "it": "Impostazioni dell'adattatore per monitor OPI",    "es": "Configuración del adaptador OPI-Monitor",         "pl": "Ustawienia adaptera OPI-Monitor",                 "zh-cn": "OPI-Monitor适配器设置"},
    "OrangePi": {                                    "en": "OrangePi",                                        "de": "OrangePi",                                        "ru": "OrangePi",                                        "pt": "OrangePi",                                        "nl": "OrangePi",                                        "fr": "OrangePi",                                        "it": "OrangePi",                                        "es": "OrangePi",                                        "pl": "OrangePi",                                        "zh-cn": "OrangePi"},
    "Swap": {                                        "en": "Swap",                                            "de": "Swap",                                            "ru": "Замена",                                          "pt": "Troca",                                           "nl": "ruil",                                            "fr": "Échanger",                                        "it": "Scambiare",                                       "es": "Intercambiar",                                    "pl": "Zamiana",                                         "zh-cn": "交换"},
    "Temperature": {                                 "en": "Temperature",                                     "de": "Temperatur",                                      "ru": "температура",                                     "pt": "Temperatura",                                     "nl": "Temperatuur",                                     "fr": "Température",                                     "it": "Temperatura",                                     "es": "Temperatura",                                     "pl": "Temperatura",                                     "zh-cn": "温度"},
    "Uptime": {                                      "en": "Uptime",                                          "de": "Uptime",                                          "ru": "Uptime",                                          "pt": "Tempo de atividade",                              "nl": "Uptime",                                          "fr": "Uptime",                                          "it": "uptime",                                          "es": "Tiempo de actividad",                             "pl": "Czas pracy",                                      "zh-cn": "正常运行时间"},
    "WLAN": {                                        "en": "WLAN",                                            "de": "WLAN",                                            "ru": "WLAN",                                            "pt": "WLAN",                                            "nl": "WLAN",                                            "fr": "WLAN",                                            "it": "WLAN",                                            "es": "WLAN",                                            "pl": "WLAN",                                            "zh-cn": "WLAN"},
    "eMMC": {                                        "en": "eMMC",                                            "de": "eMMC",                                            "ru": "EMMC",                                            "pt": "eMMC",                                            "nl": "eMMC",                                            "fr": "eMMC",                                            "it": "eMMC",                                            "es": "eMMC",                                            "pl": "eMMC",                                            "zh-cn": "的eMMC"},
};